package com.ecommerce.controller;

import java.math.BigDecimal;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import com.ecommerce.entity.EProduct;
import com.ecommerce.entity.Manufacturer;
import com.ecommerce.repositries.EProductRepositry;
import com.ecommerce.repositries.ManufacturerRepositry;

@Controller
public class ProductController {

	@Autowired
	EProductRepositry eProductRepositry;

	@Autowired
	ManufacturerRepositry manufacturerRepositry;

	@GetMapping("/add-product")
	@ResponseBody
	public String index() {
		EProduct e1 = new EProduct();
		e1.setName("HP one");
		e1.setPrice(new BigDecimal(123.5));

		Manufacturer manufacturer = new Manufacturer();
		manufacturer.setName("HP Company Inc.");			
		
		// save the manufacturer using the repo object.
		// repo then will return a manufacturer object that will have id also.
		// id is generated by the database
		manufacturer = manufacturerRepositry.save(manufacturer);
		
		e1.setManufacturer(manufacturer);
		e1 = eProductRepositry.save(e1);

		return "added eproduct with id" + e1.getID() + " it has manuafacturer with id "+manufacturer.getID();
	}

}
